### PR TITLE
Update our federation script for assigning a group to the enterprise application

### PR DESCRIPTION
**Pull request by kohei3110**
To assign a group to the enterprise app, I added new ps code.

image

### CODE REVIEW

**Comment by kohei3110** [comment]
@moisesjgomez @AnthonyDelagarde 

I've updated our script. Pls review during your free time😀

**Review by moisesjgomez — APPROVED** [review]
Looks great. We should just move line 240 to 248

**Review by sihbher — DISMISSED** [review]

**Comment by sihbher** [comment]
@kohei3110 @moisesjgomez there are some conflicts that should be addressed before merge, please take care of them

**Review by sihbher — APPROVED** [review]
LGTM

**Pull request merged**
